name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build, publish to docker hub, deploy to k8s
      - name: set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: 19
          distribution: 'adopt'
      - name: Maven Package
        run: mvn -B clean package

      - name: Build images
        run: docker-compose build

      - name: Login in docker
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Push
        run: docker-compose push

      - name: Deploy to k8s
        run: |
          kubectl config set-cluster my-cluster --server="${{ secrets.LOAD_URL }}" --insecure-skip-tls-verify=true
          kubectl config set-credentials cat7q1ukq3k3m9o35f8r --token="${{ secrets.YANDEX_TOKEN }}"
          kubectl config set-context default --cluster=my-cluster --user=cat7q1ukq3k3m9o35f8r
          kubectl config use-context default
          helm delete services && helm install services k8s/services-chart/
          sleep 90


      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v4/postman/collection.json
          environment: v4/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          images: 'library/postgres:13,gateway,reservation,library,rating'
          tail: '250'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"